### ISSUE TITLE
JFYI

### ISSUE THREAD

**Issue by CrankyYoda** [CathieNova/SPT-HavenTraderScroll#2]
So if you use  sp-eft manager ( I am guessing other add on installers will operate similarly)  the config.json installs in  bepinex>plugins instead of bepinex>config.

Just so your aware if you come across  my  config isn't there bla bla bla, Does it repopulate  config for itself in  bepinex>config?

**Comment by CathieNova** [comment]
What do you mean config.json, it should make a config inside `BepInEx\config` called `CathieNova.HavenTraderScroll.cfg`
