### ISSUE TITLE
Hidden player's money tooltip on the trader page

### ISSUE THREAD

**Issue by Deetmate** [CathieNova/SPT-HavenTraderScroll#3]
![image](https://github.com/user-attachments/assets/4b558d03-d4eb-4595-a06f-7950d9e3ffa6)
I am finding that occasionally after the first viewing of the trader screen after loading the game or out of a raid, your money tool-tip is hidden with the newest version of the trader scrolling mod
I am using many other mods on 3.10, i have tested without the scrolling plugin and seems to be related to it and some of the new UI elements.

**Comment by CathieNova** [comment]
This is fixed but not yet uploaded, had to run some errands before uploading
